export const currentData = {
  data: [
    {
      status: 200,
      data: {
        query: {
          count: 1,
          results: {
            channel: {
              location: {
                woeid: 2502265,
                city: "Sunnyvale",
                region: " CA",
                country: "United States",
                lat: 37.371609,
                long: -122.038254,
                timezone_id: "America/Los_Angeles",
              },
              item: {
                wind: {
                  chill: 59,
                  direction: 165,
                  speed: 8.7,
                },
                atmosphere: {
                  humidity: 76,
                  visibility: 10,
                  pressure: 29.68,
                },
                astronomy: {
                  sunrise: "7:23 am",
                  sunset: "5:7 pm",
                },
                units: {},
                condition: {
                  text: "Scattered Showers",
                  code: 39,
                  temp: 60,
                  date: new Date(1546934400000).toLocaleString(),
                },
                pubDate: 1546992000,
                forecasts: [
                  {
                    day: "Tue",
                    date: new Date(1546934400000).toLocaleString(),
                    low: 52,
                    high: 61,
                    text: "Rain",
                    code: 12,
                  },
                  {
                    day: "Wed",
                    date: new Date(1547020800000).toLocaleString(),
                    low: 51,
                    high: 62,
                    text: "Scattered Showers",
                    code: 39,
                  },
                  {
                    day: "Thu",
                    date: new Date(1547107200000).toLocaleString(),
                    low: 46,
                    high: 60,
                    text: "Mostly Cloudy",
                    code: 28,
                  },
                  {
                    day: "Fri",
                    date: new Date(1547193600000).toLocaleString(),
                    low: 48,
                    high: 61,
                    text: "Showers",
                    code: 11,
                  },
                  {
                    day: "Sat",
                    date: new Date(1547280000000).toLocaleString(),
                    low: 47,
                    high: 62,
                    text: "Rain",
                    code: 12,
                  },
                  {
                    day: "Sun",
                    date: new Date(1547366400000).toLocaleString(),
                    low: 48,
                    high: 58,
                    text: "Rain",
                    code: 12,
                  },
                  {
                    day: "Mon",
                    date: new Date(1547452800000).toLocaleString(),
                    low: 47,
                    high: 58,
                    text: "Rain",
                    code: 12,
                  },
                  {
                    day: "Tue",
                    date: new Date(1547539200000).toLocaleString(),
                    low: 46,
                    high: 59,
                    text: "Scattered Showers",
                    code: 39,
                  },
                  {
                    day: "Wed",
                    date: new Date(1547625600000).toLocaleString(),
                    low: 49,
                    high: 56,
                    text: "Rain",
                    code: 12,
                  },
                  {
                    day: "Thu",
                    date: new Date(1547712000000).toLocaleString(),
                    low: 49,
                    high: 59,
                    text: "Scattered Showers",
                    code: 39,
                  },
                ],
              },
            },
          },
        },
      },
    },
  ],
};

export const favPlacesArr = {
  data: [
    {
      status: 200,
      data: {
        query: {
          count: 1,
          results: {
            channel: {
              location: {
                woeid: 2502265,
                city: "Berlin",
                region: " CA",
                country: "United States",
                lat: 37.371609,
                long: -122.038254,
                timezone_id: "America/Los_Angeles",
              },
              item: {
                wind: {
                  chill: 59,
                  direction: 165,
                  speed: 8.7,
                },
                atmosphere: {
                  humidity: 76,
                  visibility: 10,
                  pressure: 29.68,
                },
                astronomy: {
                  sunrise: "7:23 am",
                  sunset: "5:7 pm",
                },
                units: {},
                condition: {
                  text: "windy",
                  code: 24,
                  temp: 50,
                  date: new Date(1546934400000).toLocaleString(),
                },
                pubDate: 1546992000,
                forecasts: [
                  {
                    day: "Tue",
                    date: new Date(1546934400000).toLocaleString(),
                    low: 52,
                    high: 61,
                    text: "Rain",
                    code: 12,
                  },
                  {
                    day: "Wed",
                    date: new Date(1547020800000).toLocaleString(),
                    low: 51,
                    high: 62,
                    text: "Scattered Showers",
                    code: 39,
                  },
                  {
                    day: "Thu",
                    date: new Date(1547107200000).toLocaleString(),
                    low: 46,
                    high: 60,
                    text: "Mostly Cloudy",
                    code: 28,
                  },
                  {
                    day: "Fri",
                    date: new Date(1547193600000).toLocaleString(),
                    low: 48,
                    high: 61,
                    text: "Showers",
                    code: 11,
                  },
                  {
                    day: "Sat",
                    date: new Date(1547280000000).toLocaleString(),
                    low: 47,
                    high: 62,
                    text: "Rain",
                    code: 12,
                  },
                  {
                    day: "Sun",
                    date: new Date(1547366400000).toLocaleString(),
                    low: 48,
                    high: 58,
                    text: "Rain",
                    code: 12,
                  },
                  {
                    day: "Mon",
                    date: new Date(1547452800000).toLocaleString(),
                    low: 47,
                    high: 58,
                    text: "Rain",
                    code: 12,
                  },
                  {
                    day: "Tue",
                    date: new Date(1547539200000).toLocaleString(),
                    low: 46,
                    high: 59,
                    text: "Scattered Showers",
                    code: 39,
                  },
                  {
                    day: "Wed",
                    date: new Date(1547625600000).toLocaleString(),
                    low: 49,
                    high: 56,
                    text: "Rain",
                    code: 12,
                  },
                  {
                    day: "Thu",
                    date: new Date(1547712000000).toLocaleString(),
                    low: 49,
                    high: 59,
                    text: "Scattered Showers",
                    code: 39,
                  },
                ],
              },
            },
          },
        },
      },
    },
    {
      status: 200,
      data: {
        query: {
          count: 1,
          results: {
            channel: {
              location: {
                woeid: 2502265,
                city: "Moscow",
                region: " CA",
                country: "United States",
                lat: 37.371609,
                long: -122.038254,
                timezone_id: "America/Los_Angeles",
              },
              item: {
                wind: {
                  chill: 59,
                  direction: 165,
                  speed: 8.7,
                },
                atmosphere: {
                  humidity: 76,
                  visibility: 10,
                  pressure: 29.68,
                },
                astronomy: {
                  sunrise: "7:23 am",
                  sunset: "5:7 pm",
                },
                units: {},
                condition: {
                  text: "thunderstorms",
                  code: 29,
                  temp: 40,
                  date: new Date(1546934400000).toLocaleString(),
                },
                pubDate: 1546992000,
                forecasts: [
                  {
                    day: "Tue",
                    date: new Date(1546934400000).toLocaleString(),
                    low: 52,
                    high: 61,
                    text: "Rain",
                    code: 12,
                  },
                  {
                    day: "Wed",
                    date: new Date(1547020800000).toLocaleString(),
                    low: 51,
                    high: 62,
                    text: "Scattered Showers",
                    code: 39,
                  },
                  {
                    day: "Thu",
                    date: new Date(1547107200000).toLocaleString(),
                    low: 46,
                    high: 60,
                    text: "Mostly Cloudy",
                    code: 28,
                  },
                  {
                    day: "Fri",
                    date: new Date(1547193600000).toLocaleString(),
                    low: 48,
                    high: 61,
                    text: "Showers",
                    code: 11,
                  },
                  {
                    day: "Sat",
                    date: new Date(1547280000000).toLocaleString(),
                    low: 47,
                    high: 62,
                    text: "Rain",
                    code: 12,
                  },
                  {
                    day: "Sun",
                    date: new Date(1547366400000).toLocaleString(),
                    low: 48,
                    high: 58,
                    text: "Rain",
                    code: 12,
                  },
                  {
                    day: "Mon",
                    date: new Date(1547452800000).toLocaleString(),
                    low: 47,
                    high: 58,
                    text: "Rain",
                    code: 12,
                  },
                  {
                    day: "Tue",
                    date: new Date(1547539200000).toLocaleString(),
                    low: 46,
                    high: 59,
                    text: "Scattered Showers",
                    code: 39,
                  },
                  {
                    day: "Wed",
                    date: new Date(1547625600000).toLocaleString(),
                    low: 49,
                    high: 56,
                    text: "Rain",
                    code: 12,
                  },
                  {
                    day: "Thu",
                    date: new Date(1547712000000).toLocaleString(),
                    low: 49,
                    high: 59,
                    text: "Scattered Showers",
                    code: 39,
                  },
                ],
              },
            },
          },
        },
      },
    },
    {
      status: 200,
      data: {
        query: {
          count: 1,
          results: {
            channel: {
              location: {
                woeid: 2502265,
                city: "Miami",
                region: " CA",
                country: "United States",
                lat: 37.371609,
                long: -122.038254,
                timezone_id: "America/Los_Angeles",
              },
              item: {
                wind: {
                  chill: 59,
                  direction: 165,
                  speed: 8.7,
                },
                atmosphere: {
                  humidity: 76,
                  visibility: 10,
                  pressure: 29.68,
                },
                astronomy: {
                  sunrise: "7:23 am",
                  sunset: "5:7 pm",
                },
                units: {},
                condition: {
                  text: "sunny",
                  code: 32,
                  temp: 60,
                  date: new Date(1546934400000).toLocaleString(),
                },
                pubDate: 1546992000,
                forecasts: [
                  {
                    day: "Tue",
                    date: new Date(1546934400000).toLocaleString(),
                    low: 52,
                    high: 61,
                    text: "Rain",
                    code: 12,
                  },
                  {
                    day: "Wed",
                    date: new Date(1547020800000).toLocaleString(),
                    low: 51,
                    high: 62,
                    text: "Scattered Showers",
                    code: 39,
                  },
                  {
                    day: "Thu",
                    date: new Date(1547107200000).toLocaleString(),
                    low: 46,
                    high: 60,
                    text: "Mostly Cloudy",
                    code: 28,
                  },
                  {
                    day: "Fri",
                    date: new Date(1547193600000).toLocaleString(),
                    low: 48,
                    high: 61,
                    text: "Showers",
                    code: 11,
                  },
                  {
                    day: "Sat",
                    date: new Date(1547280000000).toLocaleString(),
                    low: 47,
                    high: 62,
                    text: "Rain",
                    code: 12,
                  },
                  {
                    day: "Sun",
                    date: new Date(1547366400000).toLocaleString(),
                    low: 48,
                    high: 58,
                    text: "Rain",
                    code: 12,
                  },
                  {
                    day: "Mon",
                    date: new Date(1547452800000).toLocaleString(),
                    low: 47,
                    high: 58,
                    text: "Rain",
                    code: 12,
                  },
                  {
                    day: "Tue",
                    date: new Date(1547539200000).toLocaleString(),
                    low: 46,
                    high: 59,
                    text: "Scattered Showers",
                    code: 39,
                  },
                  {
                    day: "Wed",
                    date: new Date(1547625600000).toLocaleString(),
                    low: 49,
                    high: 56,
                    text: "Rain",
                    code: 12,
                  },
                  {
                    day: "Thu",
                    date: new Date(1547712000000).toLocaleString(),
                    low: 49,
                    high: 59,
                    text: "Scattered Showers",
                    code: 39,
                  },
                ],
              },
            },
          },
        },
      },
    },
    {
      status: 200,
      data: {
        query: {
          count: 1,
          results: {
            channel: {
              location: {
                woeid: 2502265,
                city: "Paris",
                region: " CA",
                country: "United States",
                lat: 37.371609,
                long: -122.038254,
                timezone_id: "America/Los_Angeles",
              },
              item: {
                wind: {
                  chill: 59,
                  direction: 165,
                  speed: 8.7,
                },
                atmosphere: {
                  humidity: 76,
                  visibility: 10,
                  pressure: 29.68,
                },
                astronomy: {
                  sunrise: "7:23 am",
                  sunset: "5:7 pm",
                },
                units: {},
                condition: {
                  text: "drizzle",
                  code: 9,
                  temp: 34,
                  date: new Date(1546934400000).toLocaleString(),
                },
                pubDate: 1546992000,
                forecasts: [
                  {
                    day: "Tue",
                    date: new Date(1546934400000).toLocaleString(),
                    low: 52,
                    high: 61,
                    text: "Rain",
                    code: 12,
                  },
                  {
                    day: "Wed",
                    date: new Date(1547020800000).toLocaleString(),
                    low: 51,
                    high: 62,
                    text: "Scattered Showers",
                    code: 39,
                  },
                  {
                    day: "Thu",
                    date: new Date(1547107200000).toLocaleString(),
                    low: 46,
                    high: 60,
                    text: "Mostly Cloudy",
                    code: 28,
                  },
                  {
                    day: "Fri",
                    date: new Date(1547193600000).toLocaleString(),
                    low: 48,
                    high: 61,
                    text: "Showers",
                    code: 11,
                  },
                  {
                    day: "Sat",
                    date: new Date(1547280000000).toLocaleString(),
                    low: 47,
                    high: 62,
                    text: "Rain",
                    code: 12,
                  },
                  {
                    day: "Sun",
                    date: new Date(1547366400000).toLocaleString(),
                    low: 48,
                    high: 58,
                    text: "Rain",
                    code: 12,
                  },
                  {
                    day: "Mon",
                    date: new Date(1547452800000).toLocaleString(),
                    low: 47,
                    high: 58,
                    text: "Rain",
                    code: 12,
                  },
                  {
                    day: "Tue",
                    date: new Date(1547539200000).toLocaleString(),
                    low: 46,
                    high: 59,
                    text: "Scattered Showers",
                    code: 39,
                  },
                  {
                    day: "Wed",
                    date: new Date(1547625600000).toLocaleString(),
                    low: 49,
                    high: 56,
                    text: "Rain",
                    code: 12,
                  },
                  {
                    day: "Thu",
                    date: new Date(1547712000000).toLocaleString(),
                    low: 49,
                    high: 59,
                    text: "Scattered Showers",
                    code: 39,
                  },
                ],
              },
            },
          },
        },
      },
    },
    {
      status: 200,
      data: {
        query: {
          count: 1,
          results: {
            channel: {
              location: {
                woeid: 2502265,
                city: "New York",
                region: " CA",
                country: "United States",
                lat: 37.371609,
                long: -122.038254,
                timezone_id: "America/Los_Angeles",
              },
              item: {
                wind: {
                  chill: 59,
                  direction: 165,
                  speed: 8.7,
                },
                atmosphere: {
                  humidity: 76,
                  visibility: 10,
                  pressure: 29.68,
                },
                astronomy: {
                  sunrise: "7:23 am",
                  sunset: "5:7 pm",
                },
                units: {},
                condition: {
                  text: "cloudy",
                  code: 26,
                  temp: 20,
                  date: new Date(1546934400000).toLocaleString(),
                },
                pubDate: 1546992000,
                forecasts: [
                  {
                    day: "Tue",
                    date: new Date(1546934400000).toLocaleString(),
                    low: 52,
                    high: 61,
                    text: "Rain",
                    code: 12,
                  },
                  {
                    day: "Wed",
                    date: new Date(1547020800000).toLocaleString(),
                    low: 51,
                    high: 62,
                    text: "Scattered Showers",
                    code: 39,
                  },
                  {
                    day: "Thu",
                    date: new Date(1547107200000).toLocaleString(),
                    low: 46,
                    high: 60,
                    text: "Mostly Cloudy",
                    code: 28,
                  },
                  {
                    day: "Fri",
                    date: new Date(1547193600000).toLocaleString(),
                    low: 48,
                    high: 61,
                    text: "Showers",
                    code: 11,
                  },
                  {
                    day: "Sat",
                    date: new Date(1547280000000).toLocaleString(),
                    low: 47,
                    high: 62,
                    text: "Rain",
                    code: 12,
                  },
                  {
                    day: "Sun",
                    date: new Date(1547366400000).toLocaleString(),
                    low: 48,
                    high: 58,
                    text: "Rain",
                    code: 12,
                  },
                  {
                    day: "Mon",
                    date: new Date(1547452800000).toLocaleString(),
                    low: 47,
                    high: 58,
                    text: "Rain",
                    code: 12,
                  },
                  {
                    day: "Tue",
                    date: new Date(1547539200000).toLocaleString(),
                    low: 46,
                    high: 59,
                    text: "Scattered Showers",
                    code: 39,
                  },
                  {
                    day: "Wed",
                    date: new Date(1547625600000).toLocaleString(),
                    low: 49,
                    high: 56,
                    text: "Rain",
                    code: 12,
                  },
                  {
                    day: "Thu",
                    date: new Date(1547712000000).toLocaleString(),
                    low: 49,
                    high: 59,
                    text: "Scattered Showers",
                    code: 39,
                  },
                ],
              },
            },
          },
        },
      },
    },
    {
      status: 200,
      data: {
        query: {
          count: 1,
          results: {
            channel: {
              location: {
                woeid: 2502265,
                city: "Toronto",
                region: " CA",
                country: "Canada",
                lat: 37.371609,
                long: -122.038254,
                timezone_id: "America/Los_Angeles",
              },
              item: {
                wind: {
                  chill: 59,
                  direction: 165,
                  speed: 8.7,
                },
                atmosphere: {
                  humidity: 76,
                  visibility: 10,
                  pressure: 29.68,
                },
                astronomy: {
                  sunrise: "7:23 am",
                  sunset: "5:7 pm",
                },
                units: {},
                condition: {
                  text: "snow",
                  code: 16,
                  temp: 23,
                  date: new Date(1546934400000).toLocaleString(),
                },
                pubDate: 1546992000,
                forecasts: [
                  {
                    day: "Tue",
                    date: new Date(1546934400000).toLocaleString(),
                    low: 52,
                    high: 61,
                    text: "Rain",
                    code: 12,
                  },
                  {
                    day: "Wed",
                    date: new Date(1547020800000).toLocaleString(),
                    low: 51,
                    high: 62,
                    text: "Scattered Showers",
                    code: 39,
                  },
                  {
                    day: "Thu",
                    date: new Date(1547107200000).toLocaleString(),
                    low: 46,
                    high: 60,
                    text: "Mostly Cloudy",
                    code: 28,
                  },
                  {
                    day: "Fri",
                    date: new Date(1547193600000).toLocaleString(),
                    low: 48,
                    high: 61,
                    text: "Showers",
                    code: 11,
                  },
                  {
                    day: "Sat",
                    date: new Date(1547280000000).toLocaleString(),
                    low: 47,
                    high: 62,
                    text: "Rain",
                    code: 12,
                  },
                  {
                    day: "Sun",
                    date: new Date(1547366400000).toLocaleString(),
                    low: 48,
                    high: 58,
                    text: "Rain",
                    code: 12,
                  },
                  {
                    day: "Mon",
                    date: new Date(1547452800000).toLocaleString(),
                    low: 47,
                    high: 58,
                    text: "Rain",
                    code: 12,
                  },
                  {
                    day: "Tue",
                    date: new Date(1547539200000).toLocaleString(),
                    low: 46,
                    high: 59,
                    text: "Scattered Showers",
                    code: 39,
                  },
                  {
                    day: "Wed",
                    date: new Date(1547625600000).toLocaleString(),
                    low: 49,
                    high: 56,
                    text: "Rain",
                    code: 12,
                  },
                  {
                    day: "Thu",
                    date: new Date(1547712000000).toLocaleString(),
                    low: 49,
                    high: 59,
                    text: "Scattered Showers",
                    code: 39,
                  },
                ],
              },
            },
          },
        },
      },
    },
  ],
};
